import nodemailer from 'nodemailer';
import { escapeHtml, renderEmailShell, renderPanel } from './_lib/emailTheme';

type NotificationType = 'booking_created' | 'quote_created' | 'invoice_created';

type NotificationPayload = {
  type?: NotificationType;
  title?: string;
  summary?: string;
  details?: Record<string, unknown>;
};

function json(res: any, status: number, body: Record<string, unknown>) {
  res.statusCode = status;
  res.setHeader('Content-Type', 'application/json');
  res.end(JSON.stringify(body));
}

function parseBody(req: any): NotificationPayload {
  if (!req?.body) {
    return {};
  }
  if (typeof req.body === 'string') {
    try {
      return JSON.parse(req.body) as NotificationPayload;
    } catch {
      return {};
    }
  }
  return req.body as NotificationPayload;
}

function getTransporter() {
  const user = process.env.SMTP_USER || 'jsuperman55@gmail.com';
  const pass = process.env.SMTP_PASS;
  if (!pass) {
    throw new Error('SMTP_PASS is not configured');
  }
  return {
    transporter: nodemailer.createTransport({
      service: 'gmail',
      auth: { user, pass },
    }),
    user,
  };
}

function normalize(value: unknown): string {
  if (value == null) {
    return '';
  }
  if (typeof value === 'string') {
    return value.trim();
  }
  return String(value);
}

function formatDetails(details?: Record<string, unknown>) {
  const entries = Object.entries(details ?? {}).filter(([, value]) => value !== undefined && value !== null && `${value}` !== '');
  const lines = entries.map(([key, value]) => `${key}: ${normalize(value)}`);
  const html = entries
    .map(
      ([key, value]) => `
        <tr>
          <td style="padding:7px 0;color:#216732;font-size:13px;line-height:1.4;vertical-align:top;">${escapeHtml(key)}</td>
          <td style="padding:7px 0;color:#0A4121;font-size:13px;line-height:1.4;font-weight:700;text-align:right;vertical-align:top;">${escapeHtml(normalize(value))}</td>
        </tr>
      `,
    )
    .join('');
  return { lines, html };
}

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return json(res, 405, { ok: false, error: 'Method not allowed' });
  }

  try {
    const payload = parseBody(req);
    if (!payload.type || !['booking_created', 'quote_created', 'invoice_created'].includes(payload.type)) {
      return json(res, 400, { ok: false, error: 'Invalid notification type' });
    }

    const title = normalize(payload.title) || payload.type.replaceAll('_', ' ');
    const summary = normalize(payload.summary);
    const { lines, html } = formatDetails(payload.details);

    const { transporter, user } = getTransporter();
    const to = process.env.NOTIFY_TO_EMAIL || 'jsuperman55@gmail.com';
    const from = process.env.EMAIL_FROM || user;
    const appUrl = (process.env.APP_URL || process.env.VITE_APP_BASE_URL || 'http://localhost:5173').replace(/\/$/, '');
    const logoUrl = `${appUrl}/images/logoEGS.png`;

    await transporter.sendMail({
      from,
      to,
      replyTo: from,
      subject: `Evergreen notification: ${title}`,
      text: ['Evergreen web notification', '', `Type: ${payload.type}`, `Title: ${title}`, summary ? `Summary: ${summary}` : '', '', ...lines]
        .filter(Boolean)
        .join('\n'),
      html: `
        ${renderEmailShell({
          eyebrow: 'Evergreen Web Event',
          title: 'Internal Notification',
          subtitle: 'Automated event update from the Evergreen web app.',
          greeting: 'Hello,',
          introHtml: `A new <strong>${escapeHtml(payload.type)}</strong> event was recorded.`,
          bodyHtml:
            renderPanel(
              'Event summary',
              `
                <div><strong>Type:</strong> ${escapeHtml(payload.type)}</div>
                <div style="margin-top:4px;"><strong>Title:</strong> ${escapeHtml(title)}</div>
                ${summary ? `<div style="margin-top:4px;"><strong>Summary:</strong> ${escapeHtml(summary)}</div>` : ''}
              `,
            ) +
            (html
              ? renderPanel(
                  'Event details',
                  `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">${html}</table>`,
                )
              : ''),
          footerNote: 'This is an internal notification email generated by the Evergreen web application.',
          logoUrl,
          preheader: `Evergreen notification: ${title}`,
        })}
      `,
    });

    return json(res, 200, { ok: true });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Failed to send notification email';
    return json(res, 500, { ok: false, error: message });
  }
}
